[versions]
kotlin = "1.8.10"
hilt = "2.44"
hilt_navigation_compose = "1.0.0"
compose_bom = "2023.01.00"
compose_compiler = "1.4.3"
compose_material_3 = "1.0.1"
nav_compose_integration = "2.6.0-alpha06"
coil = "2.2.2"
appcompat = "1.6.1"
swipe_refresh = "1.2.0-alpha01"
card_view = "1.0.0"
room = "2.5.0"
lifecycle = "2.6.0"
lifecycle_extensions = "2.2.0"
preference = "1.2.0"
timber = "5.0.1"
gson = "2.9.0"
retrofit = "2.9.0"
junit = "4.13.2"
android_test = "1.1.3"
truth = "1.1.3"
test_core = "1.5.0"
arch_core = "2.2.0"
mockk = "1.12.4"
coroutines = "1.5.1-native-mt"
espresso = "3.3.0"
test_rules_version = "1.3.0"
gradle = "7.4.2"

[libraries]
kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
swipe_refresh_layout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swipe_refresh" }
cardview = { group = "androidx.cardview", name = "cardview", version.ref = "card_view" }
room_compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room_ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room_runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
lifecycle_viewmodel_ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle_livedata_ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle_extensions = { group = "androidx.lifecycle", name = "lifecycle-extensions", version.ref = "lifecycle_extensions" }
preferences_ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit_converter_json = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
hilt_gradle_plugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hilt" }
hilt_android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt_compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt_android_compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt_navigation_compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt_navigation_compose" }
junit = { group = "junit", name = "junit", version.ref = "junit"}
arc_core_common = { group = "androidx.arch.core", name = "core-common", version.ref = "arch_core"}
arc_core_runtime = { group = "androidx.arch.core", name = "core-runtime", version.ref = "arch_core"}
arc_core_testing = { group = "androidx.arch.core", name = "core-testing", version.ref = "arch_core"}
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
kotlinx_coroutines_test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
compose_bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose_bom" }
compose_material_3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose_material_3" }
coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
navigation_compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "nav_compose_integration" }
test_core = { group= "androidx.test", name= "core", version.ref = "test_core" }
gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "gradle"}
kotlin_gradle_plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "gradle" }