[versions]
firebase-crashlytics-gradle = "2.9.9"
google-services = "4.4.0"
kotlin = "1.9.23"
compose_compiler = "1.5.10"
compose_material_3 = "1.2.0"
kotlinx-coroutines-core = "1.8.1-Beta"
kotlinx-serialization-json = "1.6.3"
multidex = "2.0.1"
nav_compose_integration = "2.7.7"
coil = "2.3.0"
appcompat = "1.6.1"
swipe_refresh = "1.2.0-alpha01"
card_view = "1.0.0"
room = "2.6.1"
lifecycle = "2.7.0"
preference = "1.2.1"
timber = "5.0.1"
gson = "2.10.1"
junit = "4.13.2"
test_core = "1.5.0"
arch_core = "2.2.0"
coroutines = "1.6.4"
gradle = "8.2.2"
firebase-crashlytics-ktx = "18.6.0"
firebase-analytics-ktx = "21.5.0"
android_youtube_player_version = "12.0.0"
core-ktx = "1.12.0"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
material = "1.11.0"
ktlint_plugin = "11.5.1"
ksp = "1.9.23-1.0.19"
kover = "0.7.5"
koin_bom = "3.6.0-wasm-alpha2"
ktor = "2.3.9"
voyager = "1.0.0"
compose_plugin = "1.6.2"
kamel_image = "0.9.3"
kotlin_stdlib = "2.0.0-Beta5"
compose = "1.6.5"
androidx_activity_compose = "1.8.2"
moko_resources = "0.23.0"
rinku = "0.1.0"

[libraries]
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebase-crashlytics-gradle" }
google-services = { module = "com.google.gms:google-services", version.ref = "google-services" }
kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
swipe_refresh_layout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swipe_refresh" }
cardview = { group = "androidx.cardview", name = "cardview", version.ref = "card_view" }
room_compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room_ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room_runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
lifecycle_viewmodel_ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle_compose_runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
preferences_ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
arc_core_common = { group = "androidx.arch.core", name = "core-common", version.ref = "arch_core" }
arc_core_runtime = { group = "androidx.arch.core", name = "core-runtime", version.ref = "arch_core" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
arc_core_testing = { group = "androidx.arch.core", name = "core-testing", version.ref = "arch_core" }
kotlinx_coroutines_test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
kotlin_test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlin_test_common = { group = "org.jetbrains.kotlin", name = "kotlin-test-common", version.ref = "kotlin" }

koin_bom = { module = "io.insert-koin:koin-bom", version.ref = "koin_bom" }
koin_core = { module = "io.insert-koin:koin-core" }
koin_android = { module = "io.insert-koin:koin-android" }
koin_androidx_compose = { module = "io.insert-koin:koin-androidx-compose" }

ui_compose_test = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose_compiler" }
compose_material_3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose_material_3" }
coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
navigation_compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "nav_compose_integration" }
test_core = { group = "androidx.test", name = "core", version.ref = "test_core" }
gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "gradle" }
kotlin_gradle_plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
firebase-crashlytics-ktx = { group = "com.google.firebase", name = "firebase-crashlytics-ktx", version.ref = "firebase-crashlytics-ktx" }
firebase-analytics-ktx = { group = "com.google.firebase", name = "firebase-analytics-ktx", version.ref = "firebase-analytics-ktx" }
android_youtube_player = { group = "com.pierfrancescosoffritti.androidyoutubeplayer", name = "core", version.ref = "android_youtube_player_version" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
ktor_client_core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor_client_okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor_client_darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktor_client_content_negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor_serialization_kotlinx_json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor_auth = { group = "io.ktor", name = "ktor-client-auth", version.ref = "ktor" }
ktor_logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
voyager_navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager_screenModel = { module = "cafe.adriel.voyager:voyager-screenmodel", version.ref = "voyager" }
voyager_koin = { module = "cafe.adriel.voyager:voyager-koin", version.ref = "voyager" }
voyager_tab_navigator = { module = "cafe.adriel.voyager:voyager-tab-navigator", version.ref = "voyager" }
kamel = { group = "media.kamel", name = "kamel-image", version.ref = "kamel_image" }
kotlin_stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin_stdlib" }
androidx_activity_compose = { module = "androidx.activity:activity-compose", version.ref = "androidx_activity_compose" }
compose_ui_tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose_ui_tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
moko_core = { group = "dev.icerock.moko", name = "resources", version.ref = "moko_resources" }
moko_compose = { group = "dev.icerock.moko", name = "resources-compose", version.ref = "moko_resources" }
rinku-core = { module= "dev.theolm:rinku", version.ref = "rinku" }
rinku-compose-ext = { module= "dev.theolm:rinku-compose-ext", version.ref = "rinku" }

[bundles]
room = ["room_ktx", "room_runtime"]
lifecycle = ["lifecycle_viewmodel_ktx", "lifecycle_compose_runtime"]
test = ["junit", "arc_core_common", "arc_core_runtime", "arc_core_testing", "kotlin_test", "kotlinx_coroutines_test"]
test_multiplatform = ["kotlin_test", "kotlin_test_common", "kotlinx_coroutines_test"]
compose_extras = ["compose_material_3", "navigation_compose"]
koin_impl = ["koin_core"]
ktor = ["ktor_client_core", "ktor_client_content_negotiation", "ktor_serialization_kotlinx_json", "ktor_auth", "ktor_logging"]
voyager = ["voyager_koin", "voyager_navigator", "voyager_screenModel"]
moko = ["moko_compose", "moko_core"]

[plugins]
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint_plugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin_multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrains_compose = { id = "org.jetbrains.compose", version.ref = "compose_plugin" }
moko_plugin = { id = "dev.icerock.mobile.multiplatform-resources", version.ref = "moko_resources" }